[project]
name = "kcj-langchain-rag-starter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arxiv>=2.4.0",
    "chromadb>=0.3.23",
    "docx2txt>=0.9",
    "faiss-cpu>=1.12.0",
    "ipykernel>=6.30.1",
    "ipywidgets>=8.1.1",
    "jq>=1.6.0",
    "jupyter>=1.0.0",
    "jupyterlab>=4.0.9",
    "langchain>=0.1.0",
    "langchain-astradb>=1.0.0,<2.0.0",
    "langchain-chroma>=0.2.6",
    "langchain-classic>=1.0.1",
    "langchain-community>=0.0.10",
    "langchain-experimental>=0.3.4",
    "langchain-google-genai>=4.2.0",
    "langchain-groq>=0.3.8",
    "langchain-huggingface>=0.3.1",
    "langchain-openai>=0.1.0",
    "langchain-pinecone>=0.2.13",
    "langchain-tavily>=0.2.17",
    "langchainhub>=0.1.15",
    "langgraph>=0.6.9",
    "langgraph-cli[inmem]>=0.4.12",
    "langgraph-supervisor>=0.0.31",
    "matplotlib>=3.10.6",
    "msoffcrypto-tool>=5.4.2",
    "notebook>=7.0.6",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pdfminer>=20191125",
    "pinecone>=7.3.0",
    "plotly>=6.5.0",
    "pymupdf>=1.26.4",
    "pypdf>=6.1.1",
    "python-docx>=1.2.0",
    "python-dotenv>=1.0.0",
    "rank-bm25>=0.2.2",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.1.1",
    "tiktoken>=0.12.0",
    "tqdm>=4.66.1",
    "unstructured>=0.18.15",
    "wikipedia>=1.4.0",
]

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"
